### ISSUE TITLE
Questions: Can debug be used in conjunction with `spring`? What about binding.pry?

### ISSUE THREAD

**Issue by machty** [st0012/ruby-lsp-rspec#14]
1. Is there a way to configure this so that the debugger process takes advantage of spring and boots more quickly? This is the difference between 6s and 3s startup when I'm running a single spec
2. If I have a `binding.pry` (because I'm still doing "old" style debugging), which pauses and requires user input from the terminal, is there a way to "exit"/continue the binding.pry? Is there any way to send keyboard strokes from the Debug Console?

**Comment by machty** [comment]
So, do people just not use spring anymore? If Ruby LSP is developed by Shopify, what sort of testing feedback loop timings are people dealing with there? How long does it take in your codebase to run a single spec 1. in normal run mode 2. in debug mode?

**Comment by st0012** [comment]
And to be absolutely clear, this is NOT a Shopify project. I built this addon simply for my other projects.

**Comment by machty** [comment]
@st0012 I'm sorry, I did not write my question with hostile intent and I'm sorry it came across that way -- I have generally felt that the Rails community is stepping away from Spring as if there is some faster alternative, but my app definitely still benefits from a perf boost when I use it, and without it my TDD cycle becomes so much slower. So I ask if people don't use Spring anymore because I'd hope it might reveal there is some other system/configuration that keeps things speedy.
