### ISSUE TITLE
Extraneous code lenses

### ISSUE THREAD

**Issue by andyw8** [st0012/ruby-lsp-rspec#17]
:wave: Not a big deal, but when trying this on https://github.com/sds/overcommit I noticed the code lenses appear on `subject`,  and on examples within `shared_examples`, which seems invalid.

**Comment by st0012** [comment]
Hmm are you sure it's from this addon? That's the 2 keywords that are currently not supported 🤔

**Comment by andyw8** [comment]
Update after talking with Stan: The `subject` issue it a bug, caused by the `context` variable:

```
subject { described_class.new(config, context) }
```

For `shared_examples`, I was meaning the examples or examples groups _within_ the `shared_examples`, since they typically wouldn't be run directly, they would be included in another group.

**Comment by st0012** [comment]
I'm not sure about `shared_examples` because I do run them directly from time to time (mostly too lazy to figure out the specific command to run them). I'd keep this behaviour for now unless more users complaint about it.

For the `context` bug, it should be fixed in #18

**Comment by st0012** [comment]
@andyw8 I've cut a release for #18 too. Thanks for reporting 👍
