### ISSUE TITLE
disable code lens decorations in rspec files 

### ISSUE THREAD

**Issue by carlost** [st0012/ruby-lsp-rspec#28]
Would it be possible to disable the "Run | Run In Terminal | Debug" decorations the extension adds? I find them a little intrusive when scanning spec files. I execute the commands linked to those decorations via shortcuts.

**Comment by st0012** [comment]
This is not under the control of this project, so please move the discussion to https://github.com/Shopify/ruby-lsp/issues/2167 🙂
