### ISSUE TITLE
When there is multiple tests without names, only the last one is executed

### ISSUE THREAD

**Issue by louim** [st0012/ruby-lsp-rspec#35]
Hello,

When multiple tests without description follow one another, only the last one is actually executed. A simple example to reproduce:

```
require 'rails_helper'

describe "MyClass" do
  subject { { a: 1, b: 2, c: 3 } }

  it { is_expected.to include(a: 1) }
  it { is_expected.to include(b: 6) }
  it { is_expected.to include(c: 3) }
end
```

When clicking run on either of those test (or on the `describe`), only the last test will actually run. A video is probably the best way to show the current behavior:

https://github.com/user-attachments/assets/1da3b521-77d8-4f97-892c-bdd803f79724

I'm running the latest versions:

#### VS Code Version

1.93.0

#### Ruby LSP Extension Version

0.7.20

#### Ruby LSP Server Version

0.17.17

#### Ruby LSP Addons

- Ruby LSP RSpec
- Ruby LSP Rails

#### Ruby Version

3.3.2

#### Ruby Version Manager

mise

#### Installed Extensions

<details>
<summary>Click to expand</summary>

- pgformatter (1.28.1)
- gitlens (15.5.0)
- EditorConfig (0.16.4)
- prettier-vscode (11.0.0)
- copilot (1.229.1104)
- copilot-chat (0.21.2024090602)
- vscode-github-actions (0.26.5)
- erb-toggle (0.1.1)
- vscode-rdbg (0.2.2)
- vsliveshare (1.0.5936)
- vscode-coverage-gutters (2.11.1)
- ruby-extensions-pack (0.1.11)
- ruby-lsp (0.7.20)
- vscode-fileutils (3.10.3)
- rewrap (1.16.3)
</details>

#### Ruby LSP Settings

<details>
<summary>Click to expand</summary>

##### Workspace

```json
{}
```

##### User

```json
{
  "enableExperimentalFeatures": true,
  "enabledFeatures": {
    "codeActions": true,
    "diagnostics": true,
    "documentHighlights": true,
    "documentLink": true,
    "documentSymbols": true,
    "foldingRanges": true,
    "formatting": true,
    "hover": true,
    "inlayHint": true,
    "onTypeFormatting": true,
    "selectionRanges": true,
    "semanticHighlighting": true,
    "completion": true,
    "codeLens": true,
    "definition": true,
    "workspaceSymbol": true,
    "signatureHelp": true,
    "typeHierarchy": true
  },
  "featuresConfiguration": {},
  "addonSettings": {},
  "rubyVersionManager": {
    "identifier": "auto"
  },
  "customRubyCommand": "",
  "formatter": "rubocop",
  "linters": null,
  "bundleGemfile": "",
  "testTimeout": 30,
  "branch": "",
  "pullDiagnosticsOn": "both",
  "useBundlerCompose": false,
  "bypassTypechecker": false,
  "rubyExecutablePath": "",
  "indexing": {},
  "erbSupport": true
}
```

</details>

**Comment by st0012** [comment]
Thanks for reporting! I've opened #40 to fix it.
