### ISSUE TITLE
Bump to latest ruby-lsp version

### ISSUE THREAD

**Issue by n-rodriguez** [st0012/ruby-lsp-rspec#36]
Hi there!

Latest `ruby-lsp` version is `0.18.2` but currently `ruby-lsp-rspec` is blocked on `0.17.x` : https://github.com/st0012/ruby-lsp-rspec/blob/f24466704f6a8c653ae7cd170ff13a3df5bab48d/ruby-lsp-rspec.gemspec#L44

Thank you!

**Comment by st0012** [comment]
Thanks for the ping. I've updated it in a new release.

**Comment by n-rodriguez** [comment]
Thank you!
