### ISSUE TITLE
Require is unusually slow

### ISSUE THREAD

**Issue by rohitpaulk** [st0012/ruby-lsp-rspec#7]
Just tried running bumbler on our app, and ruby-lsp-rspec has unusually high require times: 

```
Slow requires:
     11.73  ansi
     13.88  sentry-ruby
     14.75  stripe
     15.09  ruby-lsp-rails
     16.07  sentry-rails
     17.89  slack-ruby-client
     18.17  octokit
     19.92  resque-scheduler
     23.94  sassc-rails
     26.31  rumale
     30.85  dry-schema
     37.10  debug
     38.72  mailerlite-ruby
     39.89  omniauth-github
     42.55  rubocop-ordered_methods
     56.22  activeadmin
     56.31  appmap
     59.16  rails
    309.30  ruby-lsp-rspec
```

I'm looking into this, just opening an issue early to share findings. Took a cursory look at the gemspec, the only dependency is ruby-lsp, and the whole addon only has 2 files, so this definitely seems unexpected

**Comment by st0012** [comment]
@rohitpaulk Thank you so much for looking into this and having the PR already! 
`ruby-lsp-rspec` is not supposed to be required by the app itself at all but I forgot to add `require: false` in the readme instruction. I will open a PR for it now.

**Comment by rohitpaulk** [comment]
Awesome, thanks!
